from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Newcharacters(object):
    def setupUi(self, Newcharacters):
        Newcharacters.setObjectName("Newcharacters")
        Newcharacters.resize(779, 588)
        self.formLayoutWidget = QtWidgets.QWidget(Newcharacters)
        self.formLayoutWidget.setGeometry(QtCore.QRect(360, 10, 411, 551))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name = QtWidgets.QLabel(self.formLayoutWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name)
        self.nameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.surname = QtWidgets.QLabel(self.formLayoutWidget)
        self.surname.setObjectName("surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.surname)
        self.surnameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.surnameEdit.setObjectName("surnameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.surnameEdit)
        self.age = QtWidgets.QLabel(self.formLayoutWidget)
        self.age.setObjectName("age")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.age)
        self.ageEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ageEdit.setObjectName("ageEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ageEdit)
        self.race = QtWidgets.QLabel(self.formLayoutWidget)
        self.race.setObjectName("race")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.race)
        self.raceEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.raceEdit.setObjectName("raceEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.raceEdit)
        self.height = QtWidgets.QLabel(self.formLayoutWidget)
        self.height.setObjectName("height")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.height)
        self.heightEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.heightEdit.setObjectName("heightEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.heightEdit)
        self.weight = QtWidgets.QLabel(self.formLayoutWidget)
        self.weight.setObjectName("weight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.weight)
        self.weightEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.weightEdit.setObjectName("weightEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.weightEdit)
        self.bio = QtWidgets.QLabel(self.formLayoutWidget)
        self.bio.setObjectName("bio")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.bio)
        self.textbio = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textbio.setObjectName("textbio")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.textbio)
        self.appearance = QtWidgets.QLabel(self.formLayoutWidget)
        self.appearance.setObjectName("appearance")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.appearance)
        self.textapp = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textapp.setObjectName("textapp")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.textapp)
        self.character = QtWidgets.QLabel(self.formLayoutWidget)
        self.character.setObjectName("character")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.character)
        self.textEdit_3 = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.textEdit_3)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.gender = QtWidgets.QComboBox(self.formLayoutWidget)
        self.gender.setObjectName("comboBox")
        self.gender.addItem("")
        self.gender.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gender)
        self.imagechar = QtWidgets.QLabel(Newcharacters)
        self.imagechar.setGeometry(QtCore.QRect(20, 20, 331, 331))
        self.imagechar.setObjectName("imagechar")
        self.shows = QtWidgets.QCheckBox(Newcharacters)
        self.shows.setGeometry(QtCore.QRect(20, 420, 121, 21))
        self.shows.setObjectName("shows")
        self.saves = QtWidgets.QPushButton(Newcharacters)
        self.saves.setGeometry(QtCore.QRect(20, 510, 111, 51))
        self.saves.setObjectName("saves")
        self.char_number = QtWidgets.QComboBox(Newcharacters)
        self.char_number.setGeometry(QtCore.QRect(20, 460, 181, 23))
        self.char_number.setObjectName("char_number")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.char_number.addItem("")
        self.choose = QtWidgets.QPushButton(Newcharacters)
        self.choose.setGeometry(QtCore.QRect(20, 380, 151, 21))
        self.choose.setObjectName("choose")
        self.retranslateUi(Newcharacters)
        QtCore.QMetaObject.connectSlotsByName(Newcharacters)

    def retranslateUi(self, Newcharacters):
        _translate = QtCore.QCoreApplication.translate
        Newcharacters.setWindowTitle(_translate("Newcharacters", "Form"))
        self.name.setText(_translate("Newcharacters", "Name"))
        self.surname.setText(_translate("Newcharacters", "Surname"))
        self.age.setText(_translate("Newcharacters", "Age"))
        self.race.setText(_translate("Newcharacters", "Race"))
        self.height.setText(_translate("Newcharacters", "Height"))
        self.weight.setText(_translate("Newcharacters", "Weight"))
        self.bio.setText(_translate("Newcharacters", "Biography"))
        self.appearance.setText(_translate("Newcharacters", "Аppearance"))
        self.character.setText(_translate("Newcharacters", "Character"))
        self.label.setText(_translate("Newcharacters", "Gender"))
        self.gender.setItemText(0, _translate("Newcharacters", "Man"))
        self.gender.setItemText(1, _translate("Newcharacters", "Woman"))
        self.imagechar.setText(_translate("Newcharacters", "Here was image"))
        self.shows.setText(_translate("Newcharacters", "Show to others"))
        self.saves.setText(_translate("Newcharacters", "Save"))
        self.char_number.setItemText(0, _translate("Newcharacters", "Character_1"))
        self.char_number.setItemText(1, _translate("Newcharacters", "Character_2"))
        self.char_number.setItemText(2, _translate("Newcharacters", "Character_3"))
        self.char_number.setItemText(3, _translate("Newcharacters", "Character_4"))
        self.char_number.setItemText(4, _translate("Newcharacters", "Character_5"))
        self.char_number.setItemText(5, _translate("Newcharacters", "Character_6"))
        self.char_number.setItemText(6, _translate("Newcharacters", "Character_7"))
        self.char_number.setItemText(7, _translate("Newcharacters", "Character_8"))
        self.char_number.setItemText(8, _translate("Newcharacters", "Character_9"))
        self.char_number.setItemText(9, _translate("Newcharacters", "Character_10"))
        self.choose.setText(_translate("Newcharacters", "Choose the picture"))
