from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchUser(object):
    def setupUi(self, SearchUser):
        SearchUser.setObjectName("SearchUser")
        SearchUser.resize(717, 728)
        self.name_of_user = QtWidgets.QLineEdit(SearchUser)
        self.name_of_user.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.name_of_user.setObjectName("name_of_user")
        self.search = QtWidgets.QPushButton(SearchUser)
        self.search.setGeometry(QtCore.QRect(230, 20, 81, 31))
        self.search.setObjectName("search")
        self.photo = QtWidgets.QLabel(SearchUser)
        self.photo.setGeometry(QtCore.QRect(10, 80, 301, 291))
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.verticalLayoutWidget = QtWidgets.QWidget(SearchUser)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 70, 291, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_user.setFont(font)
        self.login_user.setText("")
        self.login_user.setObjectName("login_user")
        self.verticalLayout.addWidget(self.login_user)
        self.gender_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gender_user.setFont(font)
        self.gender_user.setText("")
        self.gender_user.setObjectName("gender_user")
        self.verticalLayout.addWidget(self.gender_user)
        self.phone_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phone_user.setFont(font)
        self.phone_user.setText("")
        self.phone_user.setObjectName("phone_user")
        self.verticalLayout.addWidget(self.phone_user)
        self.email_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.email_user.setFont(font)
        self.email_user.setText("")
        self.email_user.setObjectName("email_user")
        self.verticalLayout.addWidget(self.email_user)
        self.age_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.age_user.setFont(font)
        self.age_user.setText("")
        self.age_user.setObjectName("age_user")
        self.verticalLayout.addWidget(self.age_user)
        self.country_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.country_user.setFont(font)
        self.country_user.setText("")
        self.country_user.setObjectName("label_7")
        self.verticalLayout.addWidget(self.country_user)
        self.about_user = QtWidgets.QTextEdit(SearchUser)
        self.about_user.setGeometry(QtCore.QRect(20, 450, 671, 261))
        self.about_user.setObjectName("about_user")
        self.retranslateUi(SearchUser)
        QtCore.QMetaObject.connectSlotsByName(SearchUser)

    def retranslateUi(self, SearchUser):
        _translate = QtCore.QCoreApplication.translate
        SearchUser.setWindowTitle(_translate("SearchUser", "Form"))
        self.search.setText(_translate("SearchUser", "Search"))
